Disable cache for setup Go env in GH Action
This commit disables caching for the make verify and golangci-lint
GitHub Actions.Cache was enabled by default and was causing warning
errors like - Warning: Failed to restore: "/usr/bin/tar" failed with
error: The process '/usr/bin/tar' failed with exit code 2.

Signed-off-by: Bryan Cox <brcox@redhat.com>