Fix clsuterautoscaler command
The binary location changed in the new image, the pod fails with
CreateContainerError: stat /cluster-autoscaler: no such file or directory