api/v1alpha1: Catch up with channel, availableUpdates, and conditionalUpdates
I'd recently added these to v1beta1, but it lead to TestFuzzyConversion failures like [1]:

  --- FAIL: TestFuzzyConversion (17.55s)
      --- FAIL: TestFuzzyConversion/for_HostedCluster (13.82s)
          --- FAIL: TestFuzzyConversion/for_HostedCluster/hub-spoke-hub (0.06s)
              fuzz.go:122:
                    &v1beta1.HostedCluster{
                    	TypeMeta:   {},
                    	ObjectMeta: {Name: "實ū", GenerateName: "C", Namespace: "桵ǯƢƋIʦƯ揦Ŭõ", SelfLink: "餹擧ĳƊ6ȓŰ蓁<码竆唥鎾It¬O僸戸", ...},
                    	Spec: v1beta1.HostedClusterSpec{
                    		Release:   {Image: "Ĉy篽Õ"},
                    		ClusterID: "ȹR>迨Ǣ軃鄖5!:鏨ĭkīRU鮎",
                  - 		Channel:   "x荓!*Tt缽s览vɦrŸƻț罘`",
                  + 		Channel:   "",
  ...

The fuzzy-conversion injection seems to only be defined for v1alpha1:

  $ git grep 'for HostedCluster' | grep _test.go
  api/v1alpha1/zz_conversion_test.go:     t.Run("for HostedCluster", conversiontest.FuzzTestFunc(conversiontest.FuzzTestFuncInput{

From Cesar:

  Just make the same changes you made to the v1beta1 API to the
  v1alpha1 API. For now, to simplify conversion, we're keeping
  v1alpha1 as a superset of v1beta1 (it's essentially v1beta1 +
  several deprecated fields)

So this commit catches v1alpha1 up with my new v1beta1 properties.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_hypershift/1954/pull-ci-openshift-hypershift-main-unit/1603176003130101760